@file:Suppress("unused")

package com.computernerd1101.goban.sgf.internal

import java.lang.ref.*
import java.util.concurrent.atomic.AtomicReferenceFieldUpdater

@Suppress("UNCHECKED_CAST")
internal class WeakDateTable<T>(referent: T, val table: DateTable12<T>, val index: Int):
    WeakReference<T>(referent, table.queue as ReferenceQueue<in T>) {
    fun expunge() {
        DateTable12.weakUpdater<T>(index).compareAndSet(table, this, null)
    }
}
internal open class DateTable12<T>(@JvmField val queue: ReferenceQueue<*>) {
    @Suppress("UNCHECKED_CAST")
    companion object {
        fun <T> strongUpdater(index: Int) =
            strongUpdaters[index] as AtomicReferenceFieldUpdater<DateTable12<T>, T?>
        fun <T> weakUpdater(index: Int) =
            weakUpdaters[index] as AtomicReferenceFieldUpdater<DateTable12<T>, WeakDateTable<T>?>
        @JvmField val strongUpdaters: Array<AtomicReferenceFieldUpdater<DateTable12<*>, *>>
        @JvmField val weakUpdaters: Array<AtomicReferenceFieldUpdater<DateTable12<*>, WeakDateTable<*>?>>
        init {
            val buffer = CharArray(8)
            buffer[0] = 's'
            buffer[1] = 't'
            buffer[2] = 'r'
            buffer[3] = 'o'
            buffer[4] = 'n'
            buffer[5] = 'g'
            strongUpdaters = Array(256) { index ->
                val type = when {
                    index < 12 -> DateTable12::class.java
                    index < 128 -> DateTable128::class.java
                    else -> DateTable256::class.java
                } as Class<DateTable12<*>>
                var digit = index shr 4
                buffer[6] = (if (digit < 10) '0' else 'A' - 10) + digit
                digit = index and 0xF
                buffer[7] = (if (digit < 10) '0' else 'A' - 10) + digit
                AtomicReferenceFieldUpdater.newUpdater(type, Any::class.java, buffer.concatToString())
            }
            buffer[0] = 'w'
            buffer[1] = 'e'
            buffer[2] = 'a'
            buffer[3] = 'k'
            weakUpdaters = Array(256) { index ->
                val type = when {
                    index < 12 -> DateTable12::class.java
                    index < 128 -> DateTable128::class.java
                    else -> DateTable256::class.java
                } as Class<DateTable12<*>>
                var digit = index shr 4
                buffer[4] = (if (digit < 10) '0' else 'A' - 10) + digit
                digit = index and 0xF
                buffer[5] = (if (digit < 10) '0' else 'A' - 10) + digit
                AtomicReferenceFieldUpdater.newUpdater(type, WeakDateTable::class.java, buffer.concatToString(0, 6))
            }
        }
    }
    open val size: Int get() = 12
    @Volatile @JvmField var strong00: T? = null
    @Volatile @JvmField var weak00: WeakDateTable<T>? = null
    @Volatile @JvmField var strong01: T? = null
    @Volatile @JvmField var weak01: WeakDateTable<T>? = null
    @Volatile @JvmField var strong02: T? = null
    @Volatile @JvmField var weak02: WeakDateTable<T>? = null
    @Volatile @JvmField var strong03: T? = null
    @Volatile @JvmField var weak03: WeakDateTable<T>? = null
    @Volatile @JvmField var strong04: T? = null
    @Volatile @JvmField var weak04: WeakDateTable<T>? = null
    @Volatile @JvmField var strong05: T? = null
    @Volatile @JvmField var weak05: WeakDateTable<T>? = null
    @Volatile @JvmField var strong06: T? = null
    @Volatile @JvmField var weak06: WeakDateTable<T>? = null
    @Volatile @JvmField var strong07: T? = null
    @Volatile @JvmField var weak07: WeakDateTable<T>? = null
    @Volatile @JvmField var strong08: T? = null
    @Volatile @JvmField var weak08: WeakDateTable<T>? = null
    @Volatile @JvmField var strong09: T? = null
    @Volatile @JvmField var weak09: WeakDateTable<T>? = null
    @Volatile @JvmField var strong0A: T? = null
    @Volatile @JvmField var weak0A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong0B: T? = null
    @Volatile @JvmField var weak0B: WeakDateTable<T>? = null
}
internal open class DateTable128<T>(queue: ReferenceQueue<*>): DateTable12<T>(queue) {
    override val size: Int get() = 128
    @Volatile @JvmField var strong0C: T? = null
    @Volatile @JvmField var weak0C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong0D: T? = null
    @Volatile @JvmField var weak0D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong0E: T? = null
    @Volatile @JvmField var weak0E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong0F: T? = null
    @Volatile @JvmField var weak0F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong10: T? = null
    @Volatile @JvmField var weak10: WeakDateTable<T>? = null
    @Volatile @JvmField var strong11: T? = null
    @Volatile @JvmField var weak11: WeakDateTable<T>? = null
    @Volatile @JvmField var strong12: T? = null
    @Volatile @JvmField var weak12: WeakDateTable<T>? = null
    @Volatile @JvmField var strong13: T? = null
    @Volatile @JvmField var weak13: WeakDateTable<T>? = null
    @Volatile @JvmField var strong14: T? = null
    @Volatile @JvmField var weak14: WeakDateTable<T>? = null
    @Volatile @JvmField var strong15: T? = null
    @Volatile @JvmField var weak15: WeakDateTable<T>? = null
    @Volatile @JvmField var strong16: T? = null
    @Volatile @JvmField var weak16: WeakDateTable<T>? = null
    @Volatile @JvmField var strong17: T? = null
    @Volatile @JvmField var weak17: WeakDateTable<T>? = null
    @Volatile @JvmField var strong18: T? = null
    @Volatile @JvmField var weak18: WeakDateTable<T>? = null
    @Volatile @JvmField var strong19: T? = null
    @Volatile @JvmField var weak19: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1A: T? = null
    @Volatile @JvmField var weak1A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1B: T? = null
    @Volatile @JvmField var weak1B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1C: T? = null
    @Volatile @JvmField var weak1C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1D: T? = null
    @Volatile @JvmField var weak1D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1E: T? = null
    @Volatile @JvmField var weak1E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong1F: T? = null
    @Volatile @JvmField var weak1F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong20: T? = null
    @Volatile @JvmField var weak20: WeakDateTable<T>? = null
    @Volatile @JvmField var strong21: T? = null
    @Volatile @JvmField var weak21: WeakDateTable<T>? = null
    @Volatile @JvmField var strong22: T? = null
    @Volatile @JvmField var weak22: WeakDateTable<T>? = null
    @Volatile @JvmField var strong23: T? = null
    @Volatile @JvmField var weak23: WeakDateTable<T>? = null
    @Volatile @JvmField var strong24: T? = null
    @Volatile @JvmField var weak24: WeakDateTable<T>? = null
    @Volatile @JvmField var strong25: T? = null
    @Volatile @JvmField var weak25: WeakDateTable<T>? = null
    @Volatile @JvmField var strong26: T? = null
    @Volatile @JvmField var weak26: WeakDateTable<T>? = null
    @Volatile @JvmField var strong27: T? = null
    @Volatile @JvmField var weak27: WeakDateTable<T>? = null
    @Volatile @JvmField var strong28: T? = null
    @Volatile @JvmField var weak28: WeakDateTable<T>? = null
    @Volatile @JvmField var strong29: T? = null
    @Volatile @JvmField var weak29: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2A: T? = null
    @Volatile @JvmField var weak2A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2B: T? = null
    @Volatile @JvmField var weak2B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2C: T? = null
    @Volatile @JvmField var weak2C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2D: T? = null
    @Volatile @JvmField var weak2D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2E: T? = null
    @Volatile @JvmField var weak2E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong2F: T? = null
    @Volatile @JvmField var weak2F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong30: T? = null
    @Volatile @JvmField var weak30: WeakDateTable<T>? = null
    @Volatile @JvmField var strong31: T? = null
    @Volatile @JvmField var weak31: WeakDateTable<T>? = null
    @Volatile @JvmField var strong32: T? = null
    @Volatile @JvmField var weak32: WeakDateTable<T>? = null
    @Volatile @JvmField var strong33: T? = null
    @Volatile @JvmField var weak33: WeakDateTable<T>? = null
    @Volatile @JvmField var strong34: T? = null
    @Volatile @JvmField var weak34: WeakDateTable<T>? = null
    @Volatile @JvmField var strong35: T? = null
    @Volatile @JvmField var weak35: WeakDateTable<T>? = null
    @Volatile @JvmField var strong36: T? = null
    @Volatile @JvmField var weak36: WeakDateTable<T>? = null
    @Volatile @JvmField var strong37: T? = null
    @Volatile @JvmField var weak37: WeakDateTable<T>? = null
    @Volatile @JvmField var strong38: T? = null
    @Volatile @JvmField var weak38: WeakDateTable<T>? = null
    @Volatile @JvmField var strong39: T? = null
    @Volatile @JvmField var weak39: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3A: T? = null
    @Volatile @JvmField var weak3A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3B: T? = null
    @Volatile @JvmField var weak3B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3C: T? = null
    @Volatile @JvmField var weak3C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3D: T? = null
    @Volatile @JvmField var weak3D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3E: T? = null
    @Volatile @JvmField var weak3E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong3F: T? = null
    @Volatile @JvmField var weak3F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong40: T? = null
    @Volatile @JvmField var weak40: WeakDateTable<T>? = null
    @Volatile @JvmField var strong41: T? = null
    @Volatile @JvmField var weak41: WeakDateTable<T>? = null
    @Volatile @JvmField var strong42: T? = null
    @Volatile @JvmField var weak42: WeakDateTable<T>? = null
    @Volatile @JvmField var strong43: T? = null
    @Volatile @JvmField var weak43: WeakDateTable<T>? = null
    @Volatile @JvmField var strong44: T? = null
    @Volatile @JvmField var weak44: WeakDateTable<T>? = null
    @Volatile @JvmField var strong45: T? = null
    @Volatile @JvmField var weak45: WeakDateTable<T>? = null
    @Volatile @JvmField var strong46: T? = null
    @Volatile @JvmField var weak46: WeakDateTable<T>? = null
    @Volatile @JvmField var strong47: T? = null
    @Volatile @JvmField var weak47: WeakDateTable<T>? = null
    @Volatile @JvmField var strong48: T? = null
    @Volatile @JvmField var weak48: WeakDateTable<T>? = null
    @Volatile @JvmField var strong49: T? = null
    @Volatile @JvmField var weak49: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4A: T? = null
    @Volatile @JvmField var weak4A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4B: T? = null
    @Volatile @JvmField var weak4B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4C: T? = null
    @Volatile @JvmField var weak4C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4D: T? = null
    @Volatile @JvmField var weak4D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4E: T? = null
    @Volatile @JvmField var weak4E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong4F: T? = null
    @Volatile @JvmField var weak4F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong50: T? = null
    @Volatile @JvmField var weak50: WeakDateTable<T>? = null
    @Volatile @JvmField var strong51: T? = null
    @Volatile @JvmField var weak51: WeakDateTable<T>? = null
    @Volatile @JvmField var strong52: T? = null
    @Volatile @JvmField var weak52: WeakDateTable<T>? = null
    @Volatile @JvmField var strong53: T? = null
    @Volatile @JvmField var weak53: WeakDateTable<T>? = null
    @Volatile @JvmField var strong54: T? = null
    @Volatile @JvmField var weak54: WeakDateTable<T>? = null
    @Volatile @JvmField var strong55: T? = null
    @Volatile @JvmField var weak55: WeakDateTable<T>? = null
    @Volatile @JvmField var strong56: T? = null
    @Volatile @JvmField var weak56: WeakDateTable<T>? = null
    @Volatile @JvmField var strong57: T? = null
    @Volatile @JvmField var weak57: WeakDateTable<T>? = null
    @Volatile @JvmField var strong58: T? = null
    @Volatile @JvmField var weak58: WeakDateTable<T>? = null
    @Volatile @JvmField var strong59: T? = null
    @Volatile @JvmField var weak59: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5A: T? = null
    @Volatile @JvmField var weak5A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5B: T? = null
    @Volatile @JvmField var weak5B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5C: T? = null
    @Volatile @JvmField var weak5C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5D: T? = null
    @Volatile @JvmField var weak5D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5E: T? = null
    @Volatile @JvmField var weak5E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong5F: T? = null
    @Volatile @JvmField var weak5F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong60: T? = null
    @Volatile @JvmField var weak60: WeakDateTable<T>? = null
    @Volatile @JvmField var strong61: T? = null
    @Volatile @JvmField var weak61: WeakDateTable<T>? = null
    @Volatile @JvmField var strong62: T? = null
    @Volatile @JvmField var weak62: WeakDateTable<T>? = null
    @Volatile @JvmField var strong63: T? = null
    @Volatile @JvmField var weak63: WeakDateTable<T>? = null
    @Volatile @JvmField var strong64: T? = null
    @Volatile @JvmField var weak64: WeakDateTable<T>? = null
    @Volatile @JvmField var strong65: T? = null
    @Volatile @JvmField var weak65: WeakDateTable<T>? = null
    @Volatile @JvmField var strong66: T? = null
    @Volatile @JvmField var weak66: WeakDateTable<T>? = null
    @Volatile @JvmField var strong67: T? = null
    @Volatile @JvmField var weak67: WeakDateTable<T>? = null
    @Volatile @JvmField var strong68: T? = null
    @Volatile @JvmField var weak68: WeakDateTable<T>? = null
    @Volatile @JvmField var strong69: T? = null
    @Volatile @JvmField var weak69: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6A: T? = null
    @Volatile @JvmField var weak6A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6B: T? = null
    @Volatile @JvmField var weak6B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6C: T? = null
    @Volatile @JvmField var weak6C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6D: T? = null
    @Volatile @JvmField var weak6D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6E: T? = null
    @Volatile @JvmField var weak6E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong6F: T? = null
    @Volatile @JvmField var weak6F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong70: T? = null
    @Volatile @JvmField var weak70: WeakDateTable<T>? = null
    @Volatile @JvmField var strong71: T? = null
    @Volatile @JvmField var weak71: WeakDateTable<T>? = null
    @Volatile @JvmField var strong72: T? = null
    @Volatile @JvmField var weak72: WeakDateTable<T>? = null
    @Volatile @JvmField var strong73: T? = null
    @Volatile @JvmField var weak73: WeakDateTable<T>? = null
    @Volatile @JvmField var strong74: T? = null
    @Volatile @JvmField var weak74: WeakDateTable<T>? = null
    @Volatile @JvmField var strong75: T? = null
    @Volatile @JvmField var weak75: WeakDateTable<T>? = null
    @Volatile @JvmField var strong76: T? = null
    @Volatile @JvmField var weak76: WeakDateTable<T>? = null
    @Volatile @JvmField var strong77: T? = null
    @Volatile @JvmField var weak77: WeakDateTable<T>? = null
    @Volatile @JvmField var strong78: T? = null
    @Volatile @JvmField var weak78: WeakDateTable<T>? = null
    @Volatile @JvmField var strong79: T? = null
    @Volatile @JvmField var weak79: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7A: T? = null
    @Volatile @JvmField var weak7A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7B: T? = null
    @Volatile @JvmField var weak7B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7C: T? = null
    @Volatile @JvmField var weak7C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7D: T? = null
    @Volatile @JvmField var weak7D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7E: T? = null
    @Volatile @JvmField var weak7E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong7F: T? = null
    @Volatile @JvmField var weak7F: WeakDateTable<T>? = null
}
internal open class DateTable256<T>(queue: ReferenceQueue<*>): DateTable128<T>(queue) {
    override val size: Int get() = 256
    @Volatile @JvmField var strong80: T? = null
    @Volatile @JvmField var weak80: WeakDateTable<T>? = null
    @Volatile @JvmField var strong81: T? = null
    @Volatile @JvmField var weak81: WeakDateTable<T>? = null
    @Volatile @JvmField var strong82: T? = null
    @Volatile @JvmField var weak82: WeakDateTable<T>? = null
    @Volatile @JvmField var strong83: T? = null
    @Volatile @JvmField var weak83: WeakDateTable<T>? = null
    @Volatile @JvmField var strong84: T? = null
    @Volatile @JvmField var weak84: WeakDateTable<T>? = null
    @Volatile @JvmField var strong85: T? = null
    @Volatile @JvmField var weak85: WeakDateTable<T>? = null
    @Volatile @JvmField var strong86: T? = null
    @Volatile @JvmField var weak86: WeakDateTable<T>? = null
    @Volatile @JvmField var strong87: T? = null
    @Volatile @JvmField var weak87: WeakDateTable<T>? = null
    @Volatile @JvmField var strong88: T? = null
    @Volatile @JvmField var weak88: WeakDateTable<T>? = null
    @Volatile @JvmField var strong89: T? = null
    @Volatile @JvmField var weak89: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8A: T? = null
    @Volatile @JvmField var weak8A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8B: T? = null
    @Volatile @JvmField var weak8B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8C: T? = null
    @Volatile @JvmField var weak8C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8D: T? = null
    @Volatile @JvmField var weak8D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8E: T? = null
    @Volatile @JvmField var weak8E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong8F: T? = null
    @Volatile @JvmField var weak8F: WeakDateTable<T>? = null
    @Volatile @JvmField var strong90: T? = null
    @Volatile @JvmField var weak90: WeakDateTable<T>? = null
    @Volatile @JvmField var strong91: T? = null
    @Volatile @JvmField var weak91: WeakDateTable<T>? = null
    @Volatile @JvmField var strong92: T? = null
    @Volatile @JvmField var weak92: WeakDateTable<T>? = null
    @Volatile @JvmField var strong93: T? = null
    @Volatile @JvmField var weak93: WeakDateTable<T>? = null
    @Volatile @JvmField var strong94: T? = null
    @Volatile @JvmField var weak94: WeakDateTable<T>? = null
    @Volatile @JvmField var strong95: T? = null
    @Volatile @JvmField var weak95: WeakDateTable<T>? = null
    @Volatile @JvmField var strong96: T? = null
    @Volatile @JvmField var weak96: WeakDateTable<T>? = null
    @Volatile @JvmField var strong97: T? = null
    @Volatile @JvmField var weak97: WeakDateTable<T>? = null
    @Volatile @JvmField var strong98: T? = null
    @Volatile @JvmField var weak98: WeakDateTable<T>? = null
    @Volatile @JvmField var strong99: T? = null
    @Volatile @JvmField var weak99: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9A: T? = null
    @Volatile @JvmField var weak9A: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9B: T? = null
    @Volatile @JvmField var weak9B: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9C: T? = null
    @Volatile @JvmField var weak9C: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9D: T? = null
    @Volatile @JvmField var weak9D: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9E: T? = null
    @Volatile @JvmField var weak9E: WeakDateTable<T>? = null
    @Volatile @JvmField var strong9F: T? = null
    @Volatile @JvmField var weak9F: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA0: T? = null
    @Volatile @JvmField var weakA0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA1: T? = null
    @Volatile @JvmField var weakA1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA2: T? = null
    @Volatile @JvmField var weakA2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA3: T? = null
    @Volatile @JvmField var weakA3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA4: T? = null
    @Volatile @JvmField var weakA4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA5: T? = null
    @Volatile @JvmField var weakA5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA6: T? = null
    @Volatile @JvmField var weakA6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA7: T? = null
    @Volatile @JvmField var weakA7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA8: T? = null
    @Volatile @JvmField var weakA8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongA9: T? = null
    @Volatile @JvmField var weakA9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAA: T? = null
    @Volatile @JvmField var weakAA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAB: T? = null
    @Volatile @JvmField var weakAB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAC: T? = null
    @Volatile @JvmField var weakAC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAD: T? = null
    @Volatile @JvmField var weakAD: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAE: T? = null
    @Volatile @JvmField var weakAE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongAF: T? = null
    @Volatile @JvmField var weakAF: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB0: T? = null
    @Volatile @JvmField var weakB0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB1: T? = null
    @Volatile @JvmField var weakB1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB2: T? = null
    @Volatile @JvmField var weakB2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB3: T? = null
    @Volatile @JvmField var weakB3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB4: T? = null
    @Volatile @JvmField var weakB4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB5: T? = null
    @Volatile @JvmField var weakB5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB6: T? = null
    @Volatile @JvmField var weakB6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB7: T? = null
    @Volatile @JvmField var weakB7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB8: T? = null
    @Volatile @JvmField var weakB8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongB9: T? = null
    @Volatile @JvmField var weakB9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBA: T? = null
    @Volatile @JvmField var weakBA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBB: T? = null
    @Volatile @JvmField var weakBB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBC: T? = null
    @Volatile @JvmField var weakBC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBD: T? = null
    @Volatile @JvmField var weakBD: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBE: T? = null
    @Volatile @JvmField var weakBE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongBF: T? = null
    @Volatile @JvmField var weakBF: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC0: T? = null
    @Volatile @JvmField var weakC0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC1: T? = null
    @Volatile @JvmField var weakC1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC2: T? = null
    @Volatile @JvmField var weakC2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC3: T? = null
    @Volatile @JvmField var weakC3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC4: T? = null
    @Volatile @JvmField var weakC4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC5: T? = null
    @Volatile @JvmField var weakC5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC6: T? = null
    @Volatile @JvmField var weakC6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC7: T? = null
    @Volatile @JvmField var weakC7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC8: T? = null
    @Volatile @JvmField var weakC8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongC9: T? = null
    @Volatile @JvmField var weakC9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCA: T? = null
    @Volatile @JvmField var weakCA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCB: T? = null
    @Volatile @JvmField var weakCB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCC: T? = null
    @Volatile @JvmField var weakCC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCD: T? = null
    @Volatile @JvmField var weakCD: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCE: T? = null
    @Volatile @JvmField var weakCE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongCF: T? = null
    @Volatile @JvmField var weakCF: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD0: T? = null
    @Volatile @JvmField var weakD0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD1: T? = null
    @Volatile @JvmField var weakD1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD2: T? = null
    @Volatile @JvmField var weakD2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD3: T? = null
    @Volatile @JvmField var weakD3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD4: T? = null
    @Volatile @JvmField var weakD4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD5: T? = null
    @Volatile @JvmField var weakD5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD6: T? = null
    @Volatile @JvmField var weakD6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD7: T? = null
    @Volatile @JvmField var weakD7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD8: T? = null
    @Volatile @JvmField var weakD8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongD9: T? = null
    @Volatile @JvmField var weakD9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDA: T? = null
    @Volatile @JvmField var weakDA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDB: T? = null
    @Volatile @JvmField var weakDB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDC: T? = null
    @Volatile @JvmField var weakDC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDD: T? = null
    @Volatile @JvmField var weakDD: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDE: T? = null
    @Volatile @JvmField var weakDE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongDF: T? = null
    @Volatile @JvmField var weakDF: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE0: T? = null
    @Volatile @JvmField var weakE0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE1: T? = null
    @Volatile @JvmField var weakE1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE2: T? = null
    @Volatile @JvmField var weakE2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE3: T? = null
    @Volatile @JvmField var weakE3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE4: T? = null
    @Volatile @JvmField var weakE4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE5: T? = null
    @Volatile @JvmField var weakE5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE6: T? = null
    @Volatile @JvmField var weakE6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE7: T? = null
    @Volatile @JvmField var weakE7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE8: T? = null
    @Volatile @JvmField var weakE8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongE9: T? = null
    @Volatile @JvmField var weakE9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongEA: T? = null
    @Volatile @JvmField var weakEA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongEB: T? = null
    @Volatile @JvmField var weakEB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongEC: T? = null
    @Volatile @JvmField var weakEC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongED: T? = null
    @Volatile @JvmField var weakED: WeakDateTable<T>? = null
    @Volatile @JvmField var strongEE: T? = null
    @Volatile @JvmField var weakEE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongEF: T? = null
    @Volatile @JvmField var weakEF: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF0: T? = null
    @Volatile @JvmField var weakF0: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF1: T? = null
    @Volatile @JvmField var weakF1: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF2: T? = null
    @Volatile @JvmField var weakF2: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF3: T? = null
    @Volatile @JvmField var weakF3: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF4: T? = null
    @Volatile @JvmField var weakF4: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF5: T? = null
    @Volatile @JvmField var weakF5: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF6: T? = null
    @Volatile @JvmField var weakF6: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF7: T? = null
    @Volatile @JvmField var weakF7: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF8: T? = null
    @Volatile @JvmField var weakF8: WeakDateTable<T>? = null
    @Volatile @JvmField var strongF9: T? = null
    @Volatile @JvmField var weakF9: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFA: T? = null
    @Volatile @JvmField var weakFA: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFB: T? = null
    @Volatile @JvmField var weakFB: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFC: T? = null
    @Volatile @JvmField var weakFC: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFD: T? = null
    @Volatile @JvmField var weakFD: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFE: T? = null
    @Volatile @JvmField var weakFE: WeakDateTable<T>? = null
    @Volatile @JvmField var strongFF: T? = null
    @Volatile @JvmField var weakFF: WeakDateTable<T>? = null
}
