/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_computernerd1101_goban_test_Native */

#ifndef _Included_com_computernerd1101_goban_test_Native
#define _Included_com_computernerd1101_goban_test_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_computernerd1101_goban_test_Native
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_computernerd1101_goban_test_Native_fork
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
